# Site settings
title: CodeMonster - Programming services
email: filip.defar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Filip, and I develop software for a living.
  I'm based in Croatia, but I work remotely for clients all over the world.
  I specialize in developing web application using the Ruby language. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dabrorius.github.io" # the base hostname & protocol for your site
twitter_username: fDefar
github_username:  dabrorius
permalink: :year/:month/:title.html

# Build settings
markdown: kramdown
